[[redirects]]
  from = "/tv"
  to = "/downloads/influcine-tv-debug.apk"
  status = 302
  force = true

[[redirects]]
  from = "/install"
  to = "/downloads/influcine-tv-debug.apk"
  status = 302
  force = true

[[headers]]
  for = "/*.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment"

[[headers]]
  for = "/downloads/*.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment"

[[headers]]
  for = "/*.dmg"
  [headers.values]
    Content-Type = "application/x-apple-diskimage"
    Content-Disposition = "attachment"

[[headers]]
  for = "/*.exe"
  [headers.values]
    Content-Type = "application/vnd.microsoft.portable-executable"
    Content-Disposition = "attachment"
